apiVersion: app/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    tier: frontend
    app: nginx
spec:
  replicas: {{ .Value.deployment.replicas }}
  selector:
    matchlabels:
      tier: frontend
      app: nginx
  template:
    metadata:
      labels:
        tier: frontend
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Value.deployment.imageVersion }}
---
apiVersion: v1
kind: service
metadata:
  name: nginx
spec:
  type: {{ .Values.service.type }}
  selector:
     tier: frontend
     app: nginx
  ports:
  - name: nginx.svc.port
    protocol: TCP
    port: {{ .Value.service.port }}
    targetport: 80 # container port

