apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: expense
  labels:
    tier: frontend
    app: nginx
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      tier: frontend
      app: nginx
  template:
    metadata:
      labels:
        tier: frontend
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.deployment.imageVersion }}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: expense
spec:
  type: {{ .Values.service.type }}
  selector:
     tier: frontend
     app: nginx
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 80 # container port