apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    tier: database
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
      tier: database
      project: expense
    template:
      metadata:
        labels:
          app: mysql
          tier: database
          project: expense
      spec:
        containers:
        - name: mysql
          image: raidi/mysql:{{ .Values.deployment.imageVersion }}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    app: mysql
    tier: database
    project: expense
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306 # service port
    targetport: 3306 #container port
