apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
data:
  DB_HOST: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    project: expense
    environment: dev
    created_by: raidi
    module: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      project: expense
      environment: dev
      created_by: raidi
      module: backend
  template:
    metadata:
      labels:
        project: expense
        environment: dev
        created_by: raidi
        module: backend
    spec:
      containers:
        - name: backend
          image: raidi/backend:{{.Values.deployment.imageVersion}}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 120Mi
            limits:
              cpu: 100m
              memory: 120Mi
          envFrom:
            - configMapRef:
                name: backend
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    project: expense
    environment: dev
    created_by: raidi
    module: backend
  # type: ClusterIP
  ports:
    - name: backend
      protocol: TCP
      port: 8080
      targetPort: 8080
